#!/bin/sh
# Push a nested directory package to AUR4

set -e

cd $(dirname $0)

which mksrcinfo || exit 1

if [ $# -lt 1 ]; then
    echo "usage: $(basename $0) <path/to/project>" >&2
    exit -1
fi

git_origin=$(git remote -v | head -n 1 | grep -oP '\t[^ ]+ ' | tr -d '[:blank:]')
pkg_path=$(realpath "$1")
pkg_name=$(basename "$pkg_path")

if [ ! -d "$pkg_path" || ! -e "${pkg_path}/PKGBUILD" ]; then
    echo "$pkg_name does not contain a PKGBUILD" >&2
    exit -1
fi

[ ! -d aur4 ] && mkdir aur4
cd aur4

[ -d $pkg_name ] && rm -rf $pkg_name

git clone ssh+git://aur@aur4.archlinux.org/${pkg_name}.git/
cd $pkg_name

cp -r ../../$pkg_name/* .
mksrcinfo

git add --all
git commit -m "update from $git_origin"
git push ssh+git://aur@aur4.archlinux.org/${pkg_name}.git/
cd ../..
rm -rf aur4
